In [58]:
import numpy as np
import pandas as pd

In [59]:
dataset_test = pd.read_csv('../datasets/dataset_test.csv')
weights = pd.read_csv('./result_train_weights.csv')

In [60]:
X_test = dataset_test.select_dtypes(include=['number']).drop(columns=['Index', 'Hogwarts House', 'Care of Magical Creatures', 'Arithmancy', 'Astronomy'])
X_test = X_test.apply(lambda x: (x - x.mean()) / x.std())
X_test.fillna(0, inplace=True)

In [61]:
ones = np.ones((X_test.shape[0], 1))
X_test = np.column_stack((X_test,ones))

In [78]:
W = np.array(weights.drop(columns=weights.columns[0]))
Z = np.dot(X_test, W)
# Z.shape

(400, 4)

In [68]:
def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

In [75]:
Y_hat_test = sigmoid(Z)
# print(Y_hat_test)
# les scores des differentes classes n'est pas lies en eux. 
# L'application de sigmoid ne forme pas une distribution de proba ou la somme ne fait pad focrement 1
# les valeurs de Z sont comprime entre 0 et 1 independamment 
y_pred = np.argmax(Y_hat_test, axis=1) # classification multiclasse a partir des modeles binaires
print(y_pred)

[[0.00752782 0.0011676  0.02358796 0.99160174]
 [0.97424183 0.00565228 0.01451387 0.00464447]
 [0.00343876 0.00388837 0.99671311 0.00145059]
 ...
 [0.00822053 0.02902101 0.00715324 0.94944303]
 [0.99490489 0.01113769 0.00382336 0.00197733]
 [0.60309731 0.00201125 0.00749579 0.46556394]]
[3 0 2 3 3 1 0 3 0 3 3 1 1 1 1 3 0 1 0 3 3 1 0 0 3 3 0 1 2 0 3 3 2 3 3 0 2
 0 1 0 0 1 3 1 3 0 1 2 0 1 0 3 0 0 3 1 1 0 3 2 2 2 3 3 0 3 3 0 3 0 1 1 2 0
 2 3 3 2 0 2 0 3 1 2 2 3 3 3 0 0 3 1 2 3 0 0 2 1 3 0 3 3 3 1 0 0 3 1 1 3 3
 1 2 0 3 0 0 3 1 0 2 3 2 2 0 0 1 0 3 0 0 2 2 1 3 0 0 1 2 3 3 0 2 0 2 0 0 3
 3 0 3 2 2 0 0 2 3 1 3 0 0 3 3 3 0 1 3 3 3 3 2 3 3 1 3 2 2 3 3 1 0 0 2 1 2
 2 3 0 3 1 2 3 2 0 0 3 0 3 3 2 2 3 0 3 2 1 0 3 2 0 2 3 1 0 1 1 3 3 2 2 2 2
 3 3 2 0 0 0 3 3 2 3 1 0 3 3 3 1 2 2 3 2 3 3 2 2 0 0 3 3 1 1 3 3 0 0 3 0 3
 0 1 0 0 3 3 0 0 2 0 0 3 1 0 2 0 3 0 2 2 3 3 3 3 0 3 0 0 1 2 0 2 2 0 3 3 2
 1 3 3 3 3 3 3 3 0 1 3 0 3 1 3 3 3 2 0 3 0 1 3 1 1 0 0 1 0 0 1 3 1 2 0 3 2
 0 0 3 0 3 2 3 3 1 0 2 3 3 3 0 0 1 1 

In [65]:
houses = weights.drop(columns='Unnamed: 0')
houses = houses.columns

result = 'Index,Hogwarts Houses\n'
index = 0
for i in y_pred:
    result += f"{index},{houses[i]}\n"
    index += 1

with open('houses.csv', 'w', newline='') as file:
    file.write(result)