In [124]:
import sys
import statistic_lib as st
import numpy as np
import pandas as pd
import csv

In [149]:
dataset_test = pd.read_csv('../datasets/dataset_test.csv')
weights = pd.read_csv('./result_train_weights.csv')

In [150]:
X_test = dataset_test.select_dtypes(include=['number']).drop(columns=['Index', 'Hogwarts House', 'Care of Magical Creatures', 'Arithmancy', 'Astronomy'])
X_test = X_test.apply(lambda x: (x - x.mean()) / x.std())
X_test.fillna(0, inplace=True)

In [151]:
ones = np.ones((X_test.shape[0], 1))
X_test = np.column_stack((ones,X_test))
X_test

array([[ 1.        ,  0.32335504, -1.25481856, ..., -0.65510341,
        -0.14902972, -0.38858101],
       [ 1.        ,  0.312486  ,  0.82955394, ...,  0.85086413,
         1.36230678, -0.52137372],
       [ 1.        , -1.49767985, -0.52067217, ..., -1.22016423,
        -1.12433912,  1.85723377],
       ...,
       [ 1.        ,  0.76138236, -0.46559   , ...,  0.22336936,
        -0.09535952, -0.23236046],
       [ 1.        ,  1.05830904,  1.52420214, ...,  0.55239463,
         1.71168615, -0.43743276],
       [ 1.        ,  1.15509665,  0.        , ..., -1.64708283,
         1.43006399, -0.33773316]])

In [152]:

W = np.array(weights.drop(columns=weights.columns[0]))

Z = np.dot(X_test, W)
Z

array([[ 0.40256021, -0.34876624, -0.78826581,  0.73447184],
       [ 2.36267996, -0.31675439, -0.63580741, -1.41011816],
       [-1.65539319, -0.07824709,  2.85731607, -1.12367579],
       ...,
       [ 0.29232366, -0.96354303,  0.03755044,  0.63366893],
       [ 2.24563814, -0.20306931, -0.52229714, -1.52027169],
       [-0.28396822,  0.41637619, -0.33975604,  0.20734807]])

In [153]:
def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))  # stabilité numérique
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

Y_hat = softmax(Z)

In [154]:
print(Y_hat)

[[0.31552309 0.14884499 0.09590958 0.43972234]
 [0.87607711 0.0601006  0.04368334 0.02013895]
 [0.01013054 0.04904314 0.92358564 0.01724068]
 ...
 [0.28845377 0.08215996 0.22357828 0.40580798]
 [0.85299249 0.07370298 0.05356069 0.01974383]
 [0.17874211 0.36006641 0.16904353 0.29214795]]


In [155]:
Y_hat_test = softmax(Z)
y_pred = np.argmax(Y_hat_test, axis=1)


In [156]:
y_pred

array([3, 0, 2, 3, 3, 2, 0, 3, 0, 3, 3, 2, 2, 2, 2, 3, 0, 2, 0, 3, 3, 2,
       0, 0, 0, 0, 0, 2, 2, 0, 3, 0, 2, 3, 3, 0, 2, 0, 2, 0, 0, 2, 3, 2,
       3, 0, 2, 2, 0, 2, 0, 3, 0, 0, 3, 2, 2, 0, 0, 2, 2, 2, 0, 3, 0, 3,
       3, 0, 3, 0, 2, 2, 2, 0, 2, 0, 3, 2, 0, 2, 0, 3, 2, 2, 2, 0, 0, 3,
       0, 0, 3, 2, 2, 3, 0, 0, 2, 2, 0, 0, 3, 0, 3, 2, 0, 0, 3, 2, 2, 0,
       3, 2, 2, 0, 3, 0, 0, 0, 2, 0, 2, 3, 2, 2, 0, 0, 2, 0, 0, 0, 0, 2,
       2, 2, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 0, 3, 3, 0, 3, 2, 2, 0,
       0, 2, 3, 2, 3, 0, 0, 3, 3, 0, 0, 2, 0, 3, 3, 3, 2, 0, 3, 2, 3, 2,
       2, 3, 0, 2, 0, 0, 2, 2, 2, 2, 3, 0, 3, 2, 2, 0, 2, 0, 0, 3, 0, 3,
       3, 2, 2, 3, 0, 3, 2, 2, 0, 0, 2, 0, 2, 3, 2, 0, 2, 2, 0, 0, 2, 2,
       2, 2, 3, 3, 2, 0, 0, 0, 3, 3, 2, 3, 2, 0, 3, 3, 0, 2, 2, 2, 3, 2,
       3, 3, 2, 2, 0, 0, 3, 3, 2, 2, 3, 0, 0, 0, 3, 0, 3, 0, 2, 0, 0, 3,
       3, 0, 0, 2, 0, 0, 3, 2, 0, 2, 0, 0, 0, 2, 2, 3, 0, 3, 3, 0, 3, 0,
       0, 2, 2, 0, 2, 2, 0, 3, 3, 2, 2, 3, 3, 3, 0,